NAME=s1

clean : ;
	rm -f cols* deps* factor.easy lpindex* rels* $(NAME).fb spairs.out numFF.txt numrels.txt tmp.job *.afb.0 depinf
	rm -f $(NAME).job rows.* tmpfile.gp xprimes.jpg gmon.out spairs.add
	rm -f .params

squeaky : clean ;
	rm -f relations.jpg

