NAME=rsa100

clean : ;
	rm -f cols* deps* factor.easy lpindex* rels* numFF.txt numrels.txt tmp.job *.afb.0
	rm -f $(NAME).job $(NAME).polsel* $(NAME).fb spairs.*

squeaky : clean ;
	rm -f relations.jpg xprimes.jpg

