NAME=snfs
clean : ;
	rm -f cols* deps* factor.easy lpindex* rels* $(NAME).fb spairs.out numFF.txt numrels.txt tmp.job *.afb.0 depinf $(NAME).job

squeaky : clean ;
	rm -f relations.jpg xprimes.jpg spairs.add

